//===-- RegisterInfos_riscv64.h ----------------------------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include <stddef.h>

#include "lldb/Core/dwarf.h"
#include "llvm/Support/Compiler.h"


#ifdef DECLARE_REGISTER_INFOS_RISCV_STRUCT

enum riscv_dwarf_regnums {
  dwarf_x0 = 0,
  dwarf_x1,
  dwarf_x2,
  dwarf_x3,
  dwarf_x4,
  dwarf_x5,
  dwarf_x6,
  dwarf_x7,
  dwarf_x8,
  dwarf_x9,
  dwarf_x10,
  dwarf_x11,
  dwarf_x12,
  dwarf_x13,
  dwarf_x14,
  dwarf_x15,
  dwarf_x16,
  dwarf_x17,
  dwarf_x18,
  dwarf_x19,
  dwarf_x20,
  dwarf_x21,
  dwarf_x22,
  dwarf_x23,
  dwarf_x24,
  dwarf_x25,
  dwarf_x26,
  dwarf_x27,
  dwarf_x28,
  dwarf_x29,
  dwarf_x30,
  dwarf_x31,
  dwarf_f0 = 32,
  dwarf_f1,
  dwarf_f2,
  dwarf_f3,
  dwarf_f4,
  dwarf_f5,
  dwarf_f6,
  dwarf_f7,
  dwarf_f8,
  dwarf_f9,
  dwarf_f10,
  dwarf_f11,
  dwarf_f12,
  dwarf_f13,
  dwarf_f14,
  dwarf_f15,
  dwarf_f16,
  dwarf_f17,
  dwarf_f18,
  dwarf_f19,
  dwarf_f20,
  dwarf_f21,
  dwarf_f22,
  dwarf_f23,
  dwarf_f24,
  dwarf_f25,
  dwarf_f26,
  dwarf_f27,
  dwarf_f28,
  dwarf_f29,
  dwarf_f30,
  dwarf_f31
};

static RegisterInfo g_register_infos_rv32[] = {
    // clang-format off
    {"x0",  "zero",  4, 0, eEncodingUint,    eFormatHex,   {dwarf_x0,            dwarf_x0,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x1",  "ra",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x1,            dwarf_x1,            LLDB_REGNUM_GENERIC_RA,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x2",  "sp",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x2,            dwarf_x2,            LLDB_REGNUM_GENERIC_SP,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x3",  "gp",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x3,            dwarf_x3,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x4",  "tp",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x4,            dwarf_x4,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x5",  "t0",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x5,            dwarf_x5,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x6",  "t1",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x6,            dwarf_x6,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x7",  "t2",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x7,            dwarf_x7,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x8",  "s0",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x8,            dwarf_x8,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x9",  "s1",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x9,            dwarf_x9,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x10", "a0",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x10,           dwarf_x10,           LLDB_REGNUM_GENERIC_ARG1, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x11", "a1",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x11,           dwarf_x11,           LLDB_REGNUM_GENERIC_ARG2, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x12", "a2",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x12,           dwarf_x12,           LLDB_REGNUM_GENERIC_ARG3, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x13", "a3",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x13,           dwarf_x13,           LLDB_REGNUM_GENERIC_ARG4, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x14", "a4",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x14,           dwarf_x14,           LLDB_REGNUM_GENERIC_ARG5, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x15", "a5",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x15,           dwarf_x15,           LLDB_REGNUM_GENERIC_ARG6, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x16", "a6",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x16,           dwarf_x16,           LLDB_REGNUM_GENERIC_ARG7, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x17", "a7",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x17,           dwarf_x17,           LLDB_REGNUM_GENERIC_ARG8, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x18", "s2",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x18,           dwarf_x18,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x19", "s3",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x19,           dwarf_x19,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x20", "s4",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x20,           dwarf_x20,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x21", "s5",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x21,           dwarf_x21,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x22", "s6",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x22,           dwarf_x22,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x23", "s7",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x23,           dwarf_x23,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x24", "s8",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x24,           dwarf_x24,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x25", "s9",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x25,           dwarf_x25,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x26", "s10",   4, 0, eEncodingUint,    eFormatHex,   {dwarf_x26,           dwarf_x26,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x27", "s11",   4, 0, eEncodingUint,    eFormatHex,   {dwarf_x27,           dwarf_x27,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x28", "t3",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x28,           dwarf_x28,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x29", "t4",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x29,           dwarf_x29,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x30", "t5",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x30,           dwarf_x30,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x31", "t6",    4, 0, eEncodingUint,    eFormatHex,   {dwarf_x31,           dwarf_x31,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"pc",  nullptr, 4, 0, eEncodingUint,    eFormatHex,   {LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_PC,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f0",  "ft0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f0,            dwarf_f0,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f1",  "ft1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f1,            dwarf_f1,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f2",  "ft2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f2,            dwarf_f2,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f3",  "ft3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f3,            dwarf_f3,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f4",  "ft4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f4,            dwarf_f4,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f5",  "ft5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f5,            dwarf_f5,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f6",  "ft6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f6,            dwarf_f6,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f7",  "ft7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f7,            dwarf_f7,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f8",  "fs0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f8,            dwarf_f8,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f9",  "fs1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f9,            dwarf_f9,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f10", "fa0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f10,           dwarf_f10,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f11", "fa1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f11,           dwarf_f11,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f12", "fa2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f12,           dwarf_f12,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f13", "fa3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f13,           dwarf_f13,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f14", "fa4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f14,           dwarf_f14,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f15", "fa5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f15,           dwarf_f15,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f16", "fa6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f16,           dwarf_f16,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f17", "fa7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f17,           dwarf_f17,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f18", "fs2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f18,           dwarf_f18,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f19", "fs3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f19,           dwarf_f19,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f20", "fs4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f20,           dwarf_f20,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f21", "fs5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f21,           dwarf_f21,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f22", "fs6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f22,           dwarf_f22,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f23", "fs7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f23,           dwarf_f23,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f24", "fs8",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f24,           dwarf_f24,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f25", "fs9",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f25,           dwarf_f25,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f26", "fs10",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f26,           dwarf_f26,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f27", "fs11",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f27,           dwarf_f27,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f28", "ft8",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f28,           dwarf_f28,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f29", "ft9",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f29,           dwarf_f29,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f30", "ft10",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f30,           dwarf_f30,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f31", "ft11",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f31,           dwarf_f31,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    // clang-format on
};

static RegisterInfo g_register_infos_rv64[] = {
    // clang-format off
    {"x0",  "zero",  8, 0, eEncodingUint,    eFormatHex,   {dwarf_x0,            dwarf_x0,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x1",  "ra",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x1,            dwarf_x1,            LLDB_REGNUM_GENERIC_RA,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x2",  "sp",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x2,            dwarf_x2,            LLDB_REGNUM_GENERIC_SP,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x3",  "gp",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x3,            dwarf_x3,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x4",  "tp",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x4,            dwarf_x4,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x5",  "t0",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x5,            dwarf_x5,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x6",  "t1",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x6,            dwarf_x6,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x7",  "t2",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x7,            dwarf_x7,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x8",  "s0",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x8,            dwarf_x8,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x9",  "s1",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x9,            dwarf_x9,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x10", "a0",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x10,           dwarf_x10,           LLDB_REGNUM_GENERIC_ARG1, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x11", "a1",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x11,           dwarf_x11,           LLDB_REGNUM_GENERIC_ARG2, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x12", "a2",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x12,           dwarf_x12,           LLDB_REGNUM_GENERIC_ARG3, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x13", "a3",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x13,           dwarf_x13,           LLDB_REGNUM_GENERIC_ARG4, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x14", "a4",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x14,           dwarf_x14,           LLDB_REGNUM_GENERIC_ARG5, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x15", "a5",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x15,           dwarf_x15,           LLDB_REGNUM_GENERIC_ARG6, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x16", "a6",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x16,           dwarf_x16,           LLDB_REGNUM_GENERIC_ARG7, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x17", "a7",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x17,           dwarf_x17,           LLDB_REGNUM_GENERIC_ARG8, LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x18", "s2",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x18,           dwarf_x18,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x19", "s3",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x19,           dwarf_x19,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x20", "s4",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x20,           dwarf_x20,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x21", "s5",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x21,           dwarf_x21,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x22", "s6",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x22,           dwarf_x22,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x23", "s7",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x23,           dwarf_x23,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x24", "s8",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x24,           dwarf_x24,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x25", "s9",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x25,           dwarf_x25,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x26", "s10",   8, 0, eEncodingUint,    eFormatHex,   {dwarf_x26,           dwarf_x26,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x27", "s11",   8, 0, eEncodingUint,    eFormatHex,   {dwarf_x27,           dwarf_x27,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x28", "t3",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x28,           dwarf_x28,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x29", "t4",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x29,           dwarf_x29,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x30", "t5",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x30,           dwarf_x30,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"x31", "t6",    8, 0, eEncodingUint,    eFormatHex,   {dwarf_x31,           dwarf_x31,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"pc",  nullptr, 8, 0, eEncodingUint,    eFormatHex,   {LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM, LLDB_REGNUM_GENERIC_PC,   LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f0",  "ft0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f0,            dwarf_f0,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f1",  "ft1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f1,            dwarf_f1,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f2",  "ft2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f2,            dwarf_f2,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f3",  "ft3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f3,            dwarf_f3,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f4",  "ft4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f4,            dwarf_f4,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f5",  "ft5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f5,            dwarf_f5,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f6",  "ft6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f6,            dwarf_f6,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f7",  "ft7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f7,            dwarf_f7,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f8",  "fs0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f8,            dwarf_f8,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f9",  "fs1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f9,            dwarf_f9,            LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f10", "fa0",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f10,           dwarf_f10,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f11", "fa1",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f11,           dwarf_f11,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f12", "fa2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f12,           dwarf_f12,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f13", "fa3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f13,           dwarf_f13,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f14", "fa4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f14,           dwarf_f14,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f15", "fa5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f15,           dwarf_f15,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f16", "fa6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f16,           dwarf_f16,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f17", "fa7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f17,           dwarf_f17,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f18", "fs2",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f18,           dwarf_f18,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f19", "fs3",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f19,           dwarf_f19,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f20", "fs4",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f20,           dwarf_f20,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f21", "fs5",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f21,           dwarf_f21,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f22", "fs6",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f22,           dwarf_f22,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f23", "fs7",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f23,           dwarf_f23,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f24", "fs8",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f24,           dwarf_f24,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f25", "fs9",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f25,           dwarf_f25,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f26", "fs10",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f26,           dwarf_f26,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f27", "fs11",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f27,           dwarf_f27,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f28", "ft8",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f28,           dwarf_f28,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f29", "ft9",   4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f29,           dwarf_f29,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f30", "ft10",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f30,           dwarf_f30,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    {"f31", "ft11",  4, 0, eEncodingIEEE754, eFormatFloat, {dwarf_f31,           dwarf_f31,           LLDB_INVALID_REGNUM,      LLDB_INVALID_REGNUM, LLDB_INVALID_REGNUM}, nullptr, nullptr, nullptr, 0},
    // clang-format on
};

static const uint32_t k_num_register_infos_rv32 =
    llvm::array_lengthof(g_register_infos_rv32);
static const uint32_t k_num_register_infos_rv64 =
    llvm::array_lengthof(g_register_infos_rv64);
static bool g_register_info_names_constified = false;

#endif // DECLARE_REGISTER_INFOS_RISCV_STRUCT
